export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST"
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS"
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL"

export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL"