export const ALL_SKILLS_REQUEST = "ALL_SKILLS_REQUEST"
export const ALL_SKILLS_SUCCESS = "ALL_SKILLS_SUCCESS"
export const ALL_SKILLS_FAILS = "ALL_SKILLS_FAILS"

export const ADD_SKILL_REQUEST = "ADD_SKILL_REQUEST"
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS"
export const ADD_SKILL_FAIL = "ADD_SKILL_FAIL"

export const DELETE_SKILL_REQUEST = "DELETE_SKILL_REQUEST"
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS"
export const DELETE_SKILL_FAIL = "DELETE_SKILL_FAIL"
